const messageSelectors = [
    "div.a3s",
    "div.adn.ads",
    "div[role='listitem'] div.a3s"
];

const linkSelectors = [
    "a[href]",
    "[data-saferedirecturl]"
];

const attachmentSelectors = [
    "span.aQA",
    "div.aQH span.aV3",
    "div.aQy span"
];

let lastPayloadSignature = "";

function unique(items) {
    return [...new Set(items)];
}

function getMessageRoots() {
    const roots = [];

    for (const selector of messageSelectors) {
        document.querySelectorAll(selector).forEach((element) => {
            if (element.textContent && element.textContent.trim()) {
                roots.push(element);
            }
        });
    }

    return roots.length > 0 ? unique(roots) : [document.body];
}

function extractUrls() {
    const urls = [];

    for (const root of getMessageRoots()) {
        for (const selector of linkSelectors) {
            root.querySelectorAll(selector).forEach((link) => {
                const saferRedirectUrl = link.getAttribute("data-saferedirecturl");
                const href = saferRedirectUrl || link.getAttribute("href") || "";

                if (!href.startsWith("http")) {
                    return;
                }

                try {
                    const parsed = new URL(href);

                    if (parsed.hostname === "mail.google.com") {
                        return;
                    }

                    urls.push(parsed.toString());
                } catch {
                    // Ignore malformed href values generated by the page.
                }
            });
        }
    }

    return unique(urls);
}

function extractAttachments() {
    const attachments = [];

    for (const root of getMessageRoots()) {
        for (const selector of attachmentSelectors) {
            root.querySelectorAll(selector).forEach((element) => {
                const name = (element.textContent || "").trim();

                if (name && /\.[a-z0-9]{2,8}$/i.test(name)) {
                    attachments.push(name);
                }
            });
        }
    }

    return unique(attachments);
}

function extractSubject() {
    const subjectElement = document.querySelector("h2.hP, h2[data-thread-perm-id]");

    if (subjectElement?.textContent?.trim()) {
        return subjectElement.textContent.trim();
    }

    return document.title.replace(/\s*-\s*Gmail$/, "").trim();
}

function extractSender() {
    const senderElement = document.querySelector(".gD[email], span[email].gD, .go [email]");

    if (!senderElement) {
        return "Unknown sender";
    }

    return senderElement.getAttribute("email")
        || senderElement.getAttribute("name")
        || senderElement.textContent.trim()
        || "Unknown sender";
}

function collectEmailData() {
    return {
        subject: extractSubject(),
        sender: extractSender(),
        threadId: window.location.hash || `${extractSender()}::${extractSubject()}`,
        urls: extractUrls(),
        attachments: extractAttachments()
    };
}

function publishEmailData() {
    const data = collectEmailData();
    const payload = {
        type: "EMAIL_DATA",
        ...data
    };

    const signature = JSON.stringify(payload);

    if (signature === lastPayloadSignature) {
        return;
    }

    lastPayloadSignature = signature;

chrome.runtime.sendMessage(payload, () => {
        void chrome.runtime.lastError;
    });
}

function debounce(callback, delay) {
    let timeoutId;

    return () => {
        clearTimeout(timeoutId);
        timeoutId = setTimeout(callback, delay);
    };
}

const schedulePublish = debounce(publishEmailData, 700);

const observer = new MutationObserver(() => {
    schedulePublish();
});

observer.observe(document.documentElement, {
    childList: true,
    subtree: true
});

window.addEventListener("load", schedulePublish);
setTimeout(schedulePublish, 1500);

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type !== "EXTRACT_EMAIL_DATA") {
        return false;
    }

    const data = collectEmailData();
    lastPayloadSignature = JSON.stringify({
        type: "EMAIL_DATA",
        ...data
    });

    chrome.runtime.sendMessage({
        type: "EMAIL_DATA",
        ...data
    }, () => {
        void chrome.runtime.lastError;
    });

    sendResponse({
        ok: true,
        ...data
    });

    return true;
});
